name: announce-workflow
on: push
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use actoion
        uses: ./.github/actions/announce
        with:
          app-name: pixelpost

