name: build-info
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: print the commit , version information
        uses: ./.github/actions/build-info

