name: checks
on:
  workflow_call
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: echo something
        run: echo "hello"

