name: gated deploy
on:
  push:
    branches-ignore:
      - main
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "khushi is learning"
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: echo "because branch is main"
