name: handoff
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: date >> app.txt
      - name: upload artifaact
        uses: actions/upload-artifact@v4
        with: 
          name: app-package
          path: app.txt
  verify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: downlaod the artifact
        uses: actions/download-artifact@v4
        with:
          name: app-package
      - name: check app.txt present or not
        run: |
          if [ -f app.txt]; then
          echo "exists"
          else
            exit 1
          fi

          
