name: inspect
on: push
jobs:
  initial:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4
      - name: print vm details
        run: | 
          uname -s
          ls
      - name: print no of files
        run: find / -type f | wc -l

