name: label flow
on:
  push:
    branches-ignore:
      - main
jobs:
  labeljob:
    runs-on: ubuntu-latest
    steps:
      - name: print label
        run: echo ${{ format('build-{0}-{1}', github.run_number, github.ref_name) }}
