name: release
on: 
  push:
    branches-ignore:
      - main
jobs:
  callerjob:
    uses: ./.github/workflows/notify.yml
    with:
      environment: "tests"
    secrets:
      NOTIFY_TOKEN: ${{ secrets.NOTIFY_TOKEN }}
