name: report
on: 
  push:
    branches-ignore: 
      - main
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: write to file
        run: date >> report.txt
      - name: upload to repo artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-report
          path: report.txt
          retention-days: 5
