name: secret-check
on: push
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: mystep
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN  }}
        run: |
          if [ -n "$APP_TOKEN" ]; then
            echo "value is set"
          fi
          exit 1
        
          
